In [2]:
# coding lab 1

import numpy as np
import scipy.linalg as la

def kctb_matrices(n):
    a = np.zeros(n)
    a[0], a[1] = 2, -1
    K = la.toeplitz(a)
    
    C = K.copy()
    C[0, -1] = -1
    C[-1, 0] = -1
    C = C

    T = K.copy()
    T[0, 0] = 1
    T = T

    B = K.copy()
    B[0, 0] = 1
    B[-1, -1] = 1
    B = B

    return K, C, T, B

n = 4
K, C, T, B = kctb_matrices(n)
print("K=\n", K)
print("C=\n", C)
print("T=\n", T)
print("B=\n", B)


K=
 [[ 2. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  2.]]
C=
 [[ 2. -1.  0. -1.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [-1.  0. -1.  2.]]
T=
 [[ 1. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  2.]]
B=
 [[ 1. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  1.]]


In [3]:
# coding lab 2

def solve_hanging_system(n):
    K, C, T, B = kctb_matrices(n)
    
    H = K.copy()
    H[n-1,n-1] = 1

    f = np.ones(n)
    return la.solve(H, f)

solve = solve_hanging_system(100)
print(solve)
    

[ 100.  199.  297.  394.  490.  585.  679.  772.  864.  955. 1045. 1134.
 1222. 1309. 1395. 1480. 1564. 1647. 1729. 1810. 1890. 1969. 2047. 2124.
 2200. 2275. 2349. 2422. 2494. 2565. 2635. 2704. 2772. 2839. 2905. 2970.
 3034. 3097. 3159. 3220. 3280. 3339. 3397. 3454. 3510. 3565. 3619. 3672.
 3724. 3775. 3825. 3874. 3922. 3969. 4015. 4060. 4104. 4147. 4189. 4230.
 4270. 4309. 4347. 4384. 4420. 4455. 4489. 4522. 4554. 4585. 4615. 4644.
 4672. 4699. 4725. 4750. 4774. 4797. 4819. 4840. 4860. 4879. 4897. 4914.
 4930. 4945. 4959. 4972. 4984. 4995. 5005. 5014. 5022. 5029. 5035. 5040.
 5044. 5047. 5049. 5050.]
