In [1]:
import numpy as np
def make_K(n: int) -> np.ndarray:
    """Construct K_n with 2 on the diagonal and -1 on first off-diagonals."""
    K = 2 * np.eye(n)
    K += -1 * np.eye(n, k=1)
    K += -1 * np.eye(n, k=-1)
    return K

def inverse_K(n: int) -> np.ndarray:
    """Compute K_n^{-1} numerically."""
    K = make_K(n)
    return np.linalg.inv(K)

def inverse_K_closed_form(n: int) -> np.ndarray:
    """Closed form: (K^{-1})_ij = min(i,j)*(n+1-max(i,j))/(n+1), with i,j starting at 1."""
    i = np.arange(1, n + 1)[:, None]
    j = np.arange(1, n + 1)[None, :]
    return np.minimum(i, j) * (n + 1 - np.maximum(i, j)) / (n + 1)

n = 6
K = make_K(n)
K_inv = inverse_K(n)
K_inv_formula = inverse_K_closed_form(n)

print("K_n =\n", K)
print("\nK_n^{-1} (np.linalg.inv) =\n", np.round(K_inv, 6))
print("\nK_n^{-1} (closed form) =\n", np.round(K_inv_formula, 6))
print("\nmax|difference| =", np.max(np.abs(K_inv - K_inv_formula)))
print("max|K @ K_inv - I| =", np.max(np.abs(K @ K_inv - np.eye(n))))


K_n =
 [[ 2. -1.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0. -1.  2.]]

K_n^{-1} (np.linalg.inv) =
 [[0.857143 0.714286 0.571429 0.428571 0.285714 0.142857]
 [0.714286 1.428571 1.142857 0.857143 0.571429 0.285714]
 [0.571429 1.142857 1.714286 1.285714 0.857143 0.428571]
 [0.428571 0.857143 1.285714 1.714286 1.142857 0.571429]
 [0.285714 0.571429 0.857143 1.142857 1.428571 0.714286]
 [0.142857 0.285714 0.428571 0.571429 0.714286 0.857143]]

K_n^{-1} (closed form) =
 [[0.857143 0.714286 0.571429 0.428571 0.285714 0.142857]
 [0.714286 1.428571 1.142857 0.857143 0.571429 0.285714]
 [0.571429 1.142857 1.714286 1.285714 0.857143 0.428571]
 [0.428571 0.857143 1.285714 1.714286 1.142857 0.571429]
 [0.285714 0.571429 0.857143 1.142857 1.428571 0.714286]
 [0.142857 0.285714 0.428571 0.571429 0.714286 0.857143]]

max|difference| = 4.440892098500626e-16
max|K @ K_inv - I| = 2.220446049250313e-16
